export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const CREATE_SCORECARD_START = "CREATE_SCORECARD_START";
export const CREATE_SCORECARD_SUCCESS = "CREATE_SCORECARD_SUCCESS";
export const CREATE_SCORECARD_FAIL = "CREATE_SCORECARD_FAIL";

export const FETCH_ALL_SCORECARDS_START = "FETCH_ALL_SCORECARDS_START";
export const FETCH_ALL_SCORECARDS_SUCCESS = "FETCH_ALL_SCORECARDS_SUCCESS";
export const FETCH_ALL_SCORECARDS_FAIL = "FETCH_ALL_SCORECARDS_FAIL";

export const FETCH_SCORECARD_START = "FETCH_SCORECARD_START";
export const FETCH_SCORECARD_SUCCESS = "FETCH_SCORECARD_SUCCESS";
export const FETCH_SCORECARD_FAIL = "FETCH_SCORECARD_FAIL";

export const UPDATE_SCORE_START = "UPDATE_SCORE_START";
export const UPDATE_SCORE_SUCCESS = "UPDATE_SCORE_SUCCESS";
export const UPDATE_SCORE_FAIL = "UPDATE_SCORE_FAIL";

export const RESET_SCORECARD_START = "RESET_SCORECARD_START";
export const RESET_SCORECARD_SUCCESS = "RESET_SCORECARD_SUCCESS";
export const RESET_SCORECARD_FAIL = "RESET_SCORECARD_FAIL";

export const SUBMIT_SCORECARD_START = "SUBMIT_SCORECARD_START";
export const SUBMIT_SCORECARD_SUCCESS = "SUBMIT_SCORECARD_SUCCESS";
export const SUBMIT_SCORECARD_FAIL = "SUBMIT_SCORECARD_FAIL";
