export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const CREATE_SCORECARD_START = "CREATE_SCORECARD_START";
export const CREATE_SCORECARD_SUCCESS = "CREATE_SCORECARD_SUCCESS";
export const CREATE_SCORECARD_FAIL = "CREATE_SCORECARD_FAIL";

export const FETCH_ALL_SCORECARDS_START = "FETCH_ALL_SCORECARDS_START";
export const FETCH_ALL_SCORECARDS_SUCCESS = "FETCH_ALL_SCORECARDS_SUCCESS";
export const FETCH_ALL_SCORECARDS_FAIL = "FETCH_ALL_SCORECARDS_FAIL";

export const FETCH_SCORECARDS_START = "FETCH_SCORECARDS_START";
export const FETCH_SCORECARDS_SUCCESS = "FETCH_SCORECARDS_SUCCESS";
export const FETCH_SCORECARDS_FAIL = "FETCH_SCORECARDS_FAIL";

export const UPDATE_SCORE_START = "UPDATE_SCORE_START";
export const UPDATE_SCORE_SUCCESS = "UPDATE_SCORE_SUCCESS";
export const UPDATE_SCORE_FAIL = "UPDATE_SCORE_FAIL";

export const RESET_SCORE_START = "RESET_SCORE_START";
export const RESET_SCORE_SUCCESS = "RESET_SCORE_SUCCESS";
export const RESET_SCORE_FAIL = "RESET_SCORE_FAIL";

export const UPDATE_EVENTID = "UPDATE_EVENTID";
