export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const SCORE_UPDATE_START = "SCORE_UPDATE_START";
export const SCORE_UPDATE_SUCCESS = "SCORE_UPDATE_SUCCESS";
export const SCORE_UPDATE_FAIL = "SCORE_UPDATE_FAIL";

export const FETCH_SCORES_START = "FETCH_SCORES_START";
export const FETCH_SCORES_SUCCESS = "FETCH_SCORES_SUCCESS";
export const FETCH_SCORES_FAIL = "FETCH_SCORES_FAIL";

export const FETCH_ALL_SCORES_START = "FETCH_ALL_SCORES_START";
export const FETCH_ALL_SCORES_SUCCESS = "FETCH_ALL_SCORES_SUCCESS";
export const FETCH_ALL_SCORES_FAIL = "FETCH_ALL_SCORES_FAIL";

export const RESET_SCORE_START = "RESET_SCORE_START";
export const RESET_SCORE_SUCCESS = "RESET_SCORE_SUCCESS";
export const RESET_SCORE_FAIL = "RESET_SCORE_FAIL";

export const UPDATE_EVENTID = "UPDATE_EVENTID";
